### PR TITLE
Maximum percentage of population that can be infected so that ICU beds are still available

### PR DESCRIPTION
**Pull request by veselatereza**
https://github.com/epidemics/covid/issues/258

### CODE REVIEW

**Review by hnykda — APPROVED** [review]
Once the new regions yaml is commited, I believe we are done.

**Comment by hnykda** [comment]
@gavento can we merge - are you fine with that?

**Comment by gavento** [comment]
@veselatereza Coud you, please, rebase it on master without #11? I had to revert #11 as it broke the code in several places and will need a minor rework (some tangled merges ..) Sorry about the inconvenience ...

**Review by gavento — CHANGES_REQUESTED** [review]
Please rebase off #11 to master

**Comment by veselatereza** [comment]
@gavento Done :) you can merge it if you want or ping me if I should.

**Comment by gavento** [comment]
Rebased to updated master.
Looks good to me!
Will test it out tonight.

**Review by gavento — APPROVED** [review]

**Pull request merged**
