### PR TITLE
Estimates data prep

### PR DESCRIPTION
**Pull request by hnykda**
Definitely not finished, just to have something. But I am not sure if to continue.

Touching:
* https://github.com/epidemics/covid/issues/118
* https://github.com/epidemics/covid/issues/193
* https://github.com/epidemics/covid/issues/125
* https://github.com/epidemics/covid/issues/225
* https://github.com/epidemics/covid/issues/233

### CODE REVIEW

**Comment by lagerros** [comment]
For John Hopkins, probably want to use "null" rather than "0" when we have no data

**Comment by gavento** [comment]
Hi! I am confused - why this contains config-local and some CSVs? Just to show them?

**Comment by hnykda** [comment]
> Hi! I am confused - why this contains config-local and some CSVs? Just to show them?

Yes, just for that for reproducibility, it is definitely not something to be merged to master with data

**Comment by hnykda** [comment]
@gavento @janpipek @jez4 Jan P. just informed me that there was no notebook here, which makes this PR dumb :man_facepalming:  - I didn't push it... [Fixed](https://github.com/epidemics/epifor/blob/4193344503586bb9c0ae6a7df13872b900b05778/notebooks/csse.ipynb)

FYI I used `pycountry.countries.search_fuzzy()` quite successfully to get the iso codes where appropriate (that's how I created those maps).

**Pull request closed without merging**
