### PR TITLE
GZIP compression uploaded files

### PR DESCRIPTION
**Pull request by hnykda**
```
curl https://storage.googleapis.com/static-covid/static/data-main-v3.json > b.json
gsutil -h "Cache-Control:public, max-age=10" cp -Z -a public-read b.json gs://static-covid/static/b.json
curl https://storage.googleapis.com/static-covid/static/b.json -v --compressed
```
shows compression :raised_hands:

### CODE REVIEW

**Comment by hnykda** [comment]
Works 
image

**Review by lunemec — APPROVED** [review]
LGTM

**Comment by gavento** [comment]
:smiley:  This is surprisingly simple, thanks, Dan!

**Comment by gavento** [comment]
FYI, also added this to `gleambatch.py upload` in 786037abf8c6b9c00883ada9f5386ce642fc2325

**Pull request merged**
